### ISSUE TITLE
Incorrect results with Integer sigmas

### ISSUE THREAD

**Issue by Jimbles** [EIT-team/PEITS#1]
Voltages are ~x10 higher than expected when using a sigma =2 for all elements. Setting it to 2.0001 works.
load_sigma_vector_binary gives expected values of 2, so likely inside the solver somewhere.

This was a day of my life you took away from me markus, and I want it back

**Comment by Jimbles** [comment]
I just remembered that I didnt say what it was. If its all integers it assumes you are loading mat refs not actual sigma values. There is no indication anywhere that this is the case

**Comment by tdowrick** [comment]
Fixed with commit 25dc06b556dbe5acb3f88a24a35f4e08208421a8
