### ISSUE TITLE
Documentation is lacking...

### ISSUE THREAD

**Issue by SanaHannan** [EIT-team/PEITS#2]
things missing from markus' dune peits wiki readme
- run second long petsc installer from petsc dir
- git checkout 8695de0
- extract zoltan zip in  PEITS dir
- make build DIR
- suggest different lib dir _not_ same as repo!
- change config.opts to config.opts_example or something
- zoltan.h is missing when installing peits - forgot make install on zoltan

**Comment by tdowrick** [comment]
Install documentation added to Wiki
