### ISSUE TITLE
Clean up travis.yml file

### ISSUE THREAD

**Issue by tdowrick** [EIT-team/PEITS#3]
Too many hard coded paths

**Comment by tdowrick** [comment]
Also stop tar command printing so much to the terminal

**Comment by tdowrick** [comment]
Now using $TRAVIS_BUILD_DIR rather than hard coding, still need to stop tar printing so much

**Comment by Jimbles** [comment]
fixed with `--warning=no-unknown-keyword` flag. Added this to `update_zoltan` branch and to the install instructions
