### ISSUE TITLE
Doesn't build on Ubuntu 16.x

### ISSUE THREAD

**Issue by tdowrick** [EIT-team/PEITS#6]

**Comment by tdowrick** [comment]
Problems solved (It hink) so far:

### 'make install' for Zoltan fails.

the 'defined(x)' command is deprecated in the perl version used in 16.x

edit Zoltan_DIR/config/generate-makeoptions.pl on line 13:
change the bit with

    defined(@ARGV)

to

    @ARGV


### Accumulate is not a member of std
Add #include < numeric > to src/matlabhelpers.hh

**Comment by tdowrick** [comment]
running 'sh INSTALL' in PEITS dir fails due to:

    /usr/bin/ld: cannot find -lmpi_f90
    /usr/bin/ld: cannot find -lmpi_f77

**Comment by barryjmcd** [comment]
running 'sh INSTALL' in PEITS dir fails due to:
INSTALL gets to:
./dune-common-2.3-svn/bin/dunecontrol --opts=config.opts all

Then throws error:
config.opts: file not found
Execution of dunecontrol terminated due to errors!

**Comment by barryjmcd** [comment]
This looks helpful? http://manpages.ubuntu.com/manpages/xenial/man1/mpif77.openmpi.1.html

**Comment by tdowrick** [comment]
Good find! I'll see if I can figure out what to update to get it to work.

**Comment by barryjmcd** [comment]
This too: https://askubuntu.com/questions/822138/i-have-installed-openmpi-but-mpi-f77-is-not-created
So it may that they're now called 'mpif90',' mpif77' instead of 'mpi_f90', 'mpi_f77'. Or this 'mpifort' wrapper that covers all. Now where in the code are they being called from??

Installing libopenmpi-dev results in these (mpif77, mpif90, mpifort) in /usr/bin :
![screenshot from 2017-11-24 10-29-43](https://user-images.githubusercontent.com/7945396/33206388-fa403cae-d101-11e7-9e3a-d26b54b45a03.png)

**Comment by barryjmcd** [comment]
In the error message from running sh INSTALL see where -lmpi_77, -lmpi_90 are being called (as arguments?) in this screenshot. So I'm guessing change these calls to -lmpifort might be worth trying?
![screenshot from 2017-11-24 10-44-20](https://user-images.githubusercontent.com/7945396/33207072-306d128c-d104-11e7-83dc-2057677b3e43.png)

**Comment by tdowrick** [comment]
That seems to be right. I think it is called in the dune make/build process, which I haven't figured out how to edit yet, will have a look later if I get some time.

**Comment by barryjmcd** [comment]
Run: $ `grep -rl "mpi_f90" ~/PEITS_root`
Shows lmpi_f90, lmpi_70 appear in - 
.../PEITS_root/PEITS/src/Makefile.in
.../PEITS_root/PEITS/src/Makefile
.../PEITS_root/PEITS/src/Makefile.am

I changed them to -lmpifort (& also -lmpif90, -lmpif70) but then it can't find them! i.e. same error but now cannot find these different libraries.

Also changed them to -mpifort which give a different error (but maybe further on in the install process?).

Finally I just **took them out altogether**.. and it ran to the end without an error!? So until something else happens I'll take that as a win for now!

Update: Result of the Test Installation step seems ok:
![screenshot from 2017-11-24 11-56-16](https://user-images.githubusercontent.com/7945396/33209487-f4120036-d10d-11e7-8df1-30e9c82d5739.png)

**Comment by tdowrick** [comment]
It might be OK to just leave them out, as far as I know it doesn't actually use any Fortran code, so probably doesn't need it. I'll run through the same procedure myself and see what happens.

**Comment by barryjmcd** [comment]
When you leave them out and run `sh INSTALL`, and it goes to completion, scroll up a little in the terminal and you'll see it 'looking' for something itself that will work with the FORTRAN, since you now didn't give it a library. Anyway tell me what you think when you try it!

**Comment by tdowrick** [comment]
Tried it myself and it seems to work fine 👍

**Comment by Jimbles** [comment]
For 16.04 I had to use Zoltan v3.83, and removing the `lmpi_f90, lmpi_70` flags from `src/Makefile.am` worked!
